### ISSUE TITLE
[monica] SmartLock - IoT

### ISSUE THREAD

**Issue by davidalencar** [airjobs/monica#1]
# What is it?

Through the integration between the application and a SmartLock, the service provider can perform the work at any time, without the need to schedule a time with the owner of the residence, giving more flexibility for both.

# What are the benefits?

Make your client's life much more easier.

# Tasks

- [ ] define a lib to be used
- [ ] create the scene 
- [ ] create the components
- [ ] change the app navigation

# Reference
ref. https://github.com/airjobs/monica/issues/2#issue-372268221
