### ISSUE TITLE
Implement Unit Test

### ISSUE THREAD

**Issue by davidalencar** [airjobs/monica#11]
# What is it?

We need create automated unit test to cover the services available.

# What are the benefits?
 - Maintainability

# Tasks
- [x] Choose and implement a library to run the tests
- [x] Implement a assertion library
- [x] Choose a cover tool
- [x] Implement unit test
