### ISSUE TITLE
[monica] Face Scan

### ISSUE THREAD

**Issue by davidalencar** [airjobs/monica#4]
# What is it?

Evaluation routines are critical points of our platform and extracting the user's opinion as best as possible is our goal, so we will enrich our evaluation flow using Artificial Intelligence to understand the user's facial expression.

# What are the benefits?

The evaluation process will be more fun and attractive

# Tasks

- [x] Create new scene
- [x] Access the mobile cam
- [x] Store locally 
- [x] Consume google api
- [ ] Send result to backend

# References & Links
ref. https://github.com/airjobs/monica/issues/3
